In [ ]:
!pip install tensorflow-gpu

  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


**Word Embedding Techniques using Embedding Layer in Keras**

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
sent=["the glass of milk",
      "the glass of juice",
      "the cup of tea",
      "I am a good boy",
      "I am a good devloper",
      "understand the meaning of words",
      "your videos are good"]

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good devloper',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
## Vocubulary size
voc_size=500

**One Hot Representation**

In [ ]:
onehot_repr=[one_hot(words, voc_size) for words in sent]
print(onehot_repr)

[[384, 183, 340, 43], [384, 183, 340, 166], [384, 53, 340, 98], [386, 358, 87, 175, 328], [386, 358, 87, 175, 177], [32, 384, 15, 340, 115], [440, 118, 60, 175]]


In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
## pre paddding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 384 183 340  43]
 [  0   0   0   0 384 183 340 166]
 [  0   0   0   0 384  53 340  98]
 [  0   0   0 386 358  87 175 328]
 [  0   0   0 386 358  87 175 177]
 [  0   0   0  32 384  15 340 115]
 [  0   0   0   0 440 118  60 175]]


In [ ]:
## 10 feature dimensions
dim=10

In [ ]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5000 (19.53 KB)
Trainable params: 5000 (19.53 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
## 'the glass of milk,
embedded_docs[0]

array([  0,   0,   0,   0, 384, 183, 340,  43], dtype=int32)

In [ ]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 105ms/step


array([[ 0.04382252,  0.02489794,  0.04069808, -0.0092678 ,  0.02741071,
         0.03469196,  0.04815098, -0.02835548,  0.03046911,  0.01331208],
       [ 0.04382252,  0.02489794,  0.04069808, -0.0092678 ,  0.02741071,
         0.03469196,  0.04815098, -0.02835548,  0.03046911,  0.01331208],
       [ 0.04382252,  0.02489794,  0.04069808, -0.0092678 ,  0.02741071,
         0.03469196,  0.04815098, -0.02835548,  0.03046911,  0.01331208],
       [ 0.04382252,  0.02489794,  0.04069808, -0.0092678 ,  0.02741071,
         0.03469196,  0.04815098, -0.02835548,  0.03046911,  0.01331208],
       [ 0.01227101, -0.0394947 , -0.00966777, -0.01316142,  0.01606849,
        -0.04887921, -0.01261168, -0.01865089,  0.03273659,  0.02365435],
       [ 0.02673805,  0.0360315 ,  0.01992315,  0.03068899, -0.03489194,
        -0.03445292, -0.03620588,  0.00055482,  0.00106256,  0.0095722 ],
       [ 0.01079465, -0.04775337,  0.03583357,  0.02685031, -0.00366639,
         0.01373849,  0.04680859, -0.03976976